FROM python:3.10

RUN apt-get update \
    && apt-get install -y \
        build-essential \
        clang \
        cmake \
        libedit-dev \
        lld \
        llvm \
        swig \
        zstd \
    && rm -rf /var/lib/apt/lists/*
